# Generated by Django 2.0.5 on 2018-11-06 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='updated_date',
            field=models.DateField(default=datetime.date(2018, 11, 6)),
        ),
    ]
