# Generated by Django 2.0.5 on 2018-11-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icsApp', '0003_auto_20181106_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
