# Generated by Django 2.0.5 on 2018-12-07 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icsApp', '0004_auto_20181106_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='updated_date',
            field=models.DateField(default=datetime.date(2018, 12, 7)),
        ),
    ]
