# Generated by Django 2.0.5 on 2018-12-19 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icsApp', '0005_auto_20181207_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='updated_date',
            field=models.DateField(default=datetime.date(2018, 12, 19)),
        ),
    ]
